### ISSUE TITLE
__version__

### ISSUE THREAD

**Issue by TyberiusPrime** [PyO3/pyo3-pack#100]
It would be cool if pyo3-pack packages defined their __version__ to be the one from cargo.toml automatically.

In the meanwhile, how would I define such a static string for my pymodule?

**Comment by konstin** [comment]
I assume you're using pyo3 or rust-cpython, things are different for cffi.

While pyo3-pack adds the version from Cargo.toml as the packages version, it can't really change your python module. However, you can easily add `__version__` yourself with 

```
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
```

I think that this should become part of the pyo3 docs, and you might also want to have a look at https://github.com/PyO3/pyo3-built/, even though it's a bit outdated.

**Comment by TyberiusPrime** [comment]
Sometimes, at the end of a long day of coding, you find that something is just as easy as it should be.
This will work nicely for me - and yes it's a good idea to maybe even add it to the 'this is how you do a python module' example on PyO3.
