### ISSUE TITLE
How to generate windows wheels?

### ISSUE THREAD

**Issue by brupelo** [PyO3/pyo3-pack#101]
Hello, first of all let me tell you this project is really nice, 1 command will produce wheels...  Before this I'd tried setuptools-rust and the process was quite tricky :/

Anyway, got a couple of questions, right now I've been able to generate wheels for linux by using the undocummented `--release` suffix using a command like:

    `docker run -it -v `pwd`:/io konstin2/pyo3-pack build`

And the above command has generated me 4 wheels:

    pysyntect-0.0.1-cp27-cp27mu-manylinux1_x86_64.whl
    pysyntect-0.0.1-cp35-cp35m-manylinux1_x86_64.whl
    pysyntect-0.0.1-cp36-cp36m-manylinux1_x86_64.whl
    pysyntect-0.0.1-cp37-cp37m-manylinux1_x86_64.whl

**1st issue**

So far so good... Now I was trying to figure out how to do the same on windows7 but some errors have appeared... take a look:

    (py364_32) D:\sources\personal\python\pysyntect>pyo3-pack list-python
    Could not find any interpreters, are you sure you have python installed on your PATH?

    (py364_32) D:\sources\personal\python\pysyntect>pyo3-pack build
    🔗 Found pyo3 bindings
    Could not find any interpreters, are you sure you have python installed on your PATH?

As you can see, I'm calling pyo3-pack build from my activated virtualenv (python is on PATH!!!).

**2nd issue**

I would be interested to generate wheels for windows/linux && cp36-cp36m... that's all, the rest of platforms (cp27,cp35,cp37) are pretty much irrelevant to me, isn't possible to specify that somehow to pyo3-pack?

Thanks in advance!

Ps. Isn't there any irc channel on freenode/moznet to discuss stuff about pyo3, setuptools-rust, pyo3-pack? I see there is gitter... but I prefer using IRC ;)

**Comment by brupelo** [comment]
Btw, you can see here an example of what I've uploaded right now... [https://github.com/brupelo/pyblime/releases](https://github.com/brupelo/pyblime/releases). All of it should be wheels... not pyd+.whl files :(

**Comment by brupelo** [comment]
Today I've uploaded the rust project that uses pyo3... and as you can see, right now I haven't been able to figure out how to provide windows wheels [here](https://github.com/brupelo/pysyntect/releases) :(

**Comment by konstin** [comment]
Re building on windows: The error message is misleading here; pyo3-pack expects the python launcher `py` and not `python` to be in scope because the python launcher allows using multiple python versions. Using `--interpreter python` should work even without the python interpreter.

> Today I've uploaded the rust project that uses pyo3... and as you can see, right now I haven't been able to figure out how to provide windows wheels here :(

pyo3-pack got nothing to do with github releases, it's only for uploading to pypi

> Ps. Isn't there any irc channel on freenode/moznet to discuss stuff about pyo3, setuptools-rust, pyo3-pack? I see there is gitter... but I prefer using IRC ;)

No, we've chosen gitter. On tbh I don't appreciate it if others try to tell me which platforms to use or create channels with the name of the project

**Comment by brupelo** [comment]
Just one little note here:

"Isn't there any irc channel on freenode/moznet to discuss stuff about pyo3, setuptools-rust, pyo3-pack? I see there is gitter... but I prefer using IRC ;)"

I wasn't trying to tell you which platform to use or which channels to create for your project... I was just asking in case anyone else could be interested on IRC so please don't take it like I'm bossing around cos I'm not, no IRC channels in addition to gitter? Sure, that's fine with me.

**Comment by brupelo** [comment]
Btw, yeah, `--interpreter python` worked quite nicely! Thanks about it ;)
