### ISSUE TITLE
manylinux docker image issues

### ISSUE THREAD

**Issue by omerbenamram** [PyO3/pyo3-pack#123]
I've tried the official docker image with pyo3 0.6.0, and the master with pyo3 0.7.0 alpha1.

It seems to always complain about missing libpython.

Running it like this:
`docker run --rm -v (pwd):/io 10c0135f4da7 build` (`10c0135f4da7` being master version of docker image)

```
🔗 Found pyo3 bindings
🐍 Found CPython 3.5m at python3.5, CPython 3.6m at python3.6, CPython 3.7m at python3.7
   Compiling pyo3 v0.7.0-alpha.1
error: could not find native static library `python3.5m`, perhaps an -L flag is missing?


error: aborting due to previous error


error: Could not compile `pyo3`.

To learn more, run the command again with --verbose.
Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --features pyo3/python3 --lib --`
Failed to build a native library through cargo
```

It seems from a quick glace inside the container that libpython is nowhere to be found.
```
[root@dca866f6dbb7 /]# find . -iname "*libpython*.so*"
./usr/lib64/libpython2.4.so
./usr/lib64/libpython2.4.so.1.0
[root@dca866f6dbb7 /]#
```

Am I missing something?

**Comment by omerbenamram** [comment]
Resolved when building `pyo3` with `extension-module` feature. :)

**Comment by konstin** [comment]
The error message for that is really bad. I've added a warning when `extension-module` is missing in #126
