### ISSUE TITLE
broken wheels (macOS)

### ISSUE THREAD

**Issue by omerbenamram** [PyO3/pyo3-pack#124]
Currently wheels produced with `pyo3-pack` are not working in macOS (maybe on other platforms as well?).

I initially though this is related to https://github.com/PyO3/pyo3/issues/341, but I've tried reverting to `pyo3 0.5.4` and the issue persisted.

I'm using the `extension-module` feature.

I'm getting the following error:
```
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import evtx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_evtx)
>>>
```

And for wheels setuptools-rust with `python setup.py bdist_wheel` it's working as expected.

```
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import evtx
>>>
```

All the code is public at https://github.com/omerbenamram/pyevtx-rs

Any thoughts?

**Comment by konstin** [comment]
Sounds like a naming mismatch. Try renaming https://github.com/omerbenamram/pyevtx-rs/blob/master/src/lib.rs#L115 from `parser` to `evtx`

**Comment by omerbenamram** [comment]
@konstin It works!

If there's any way it could have warned me against this (I'm not sure it's possible) that would have been awesome! Thanks again for this awesome tool :)

**Comment by messense** [comment]
https://github.com/PyO3/maturin/pull/528 added missing `PyInit_<module_name>` symbol export warning for macOS.
