### ISSUE TITLE
Manylinux2010 does not seem to be correctly supported

### ISSUE THREAD

**Issue by thedrow** [PyO3/pyo3-pack#147]
I built a wheel for manylinux2010 using pyo3-pack.

After I built it I run auditwheel myself and I was surprised by the result:

```
fastuuid-0.1.0-cp35-cp35m-manylinux2010_x86_64.whl is consistent with
the following platform tag: "manylinux1_x86_64".
```

I am building that wheel using the manylinux2010 docker image so I'm supposed to get a manylinux2010 wheel.

Either `auditwheel` is wrong or we are not doing something we should be doing.
What do you think?

**Comment by konstin** [comment]
Please post the commands required to reproduce the message you got. 

> I am building that wheel using the manylinux2010 docker image so I'm supposed to get a manylinux2010 wheel.

No, the platform tag is controlled solely by the cli options and the python interpreter.

**Comment by thedrow** [comment]
- Clone the [fastuuid](https://github.com/thedrow/fastuuid/) repository.
- Build the docker image for [manylinux2010](https://github.com/thedrow/fastuuid/blob/master/manylinux2010.dockerfile).
`sudo docker build -f manylinux2010.dockerfile -t fastuuid_manylinux2010:latest`
- Run the container using the following command:
`sudo docker run -e MANYLINUX_VERSION="2010" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e PYO3_PACK_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src fastuuid_manylinux2010:latest`

The command that should be executed is:
```
/opt/python/cp37-cp37m/bin/pyo3-pack build --manylinux 2010 --release -i /opt/python/cp37-cp37m/bin/python -i /opt/python/cp36-cp36m/bin/python -i /opt/python/cp35-cp35m/bin/python
```

**Comment by konstin** [comment]
It looks like that's just auditwheel being weird. Judging from [the code producing the message](https://github.com/pypa/auditwheel/blob/7e2928eb75e2a11f62d6754bca5bafedbb09e091/auditwheel/main_show.py#L35-L38), it's not an error but just a message to tell that {chosen platform tag} is ok with {lowest possible platform tag}. The list of linked symbols and libs printed below is compatible with manylinux1, so in that context the message makes sense. I've also checked the wheels and the in-wheel metadata definitely says manylinux2010.

**Comment by thedrow** [comment]
So should I build both or simply `auditwheel repair`?

**Comment by konstin** [comment]
I'd say just build manylinux1 wheels; I don't see any reason for building manylinux2010 wheels or for running auditwheel. manylinux2010 [isn't even fully rolled out yet](https://github.com/pypa/manylinux/issues/179).
