### ISSUE TITLE
pyo3-pack does not compile, because structopt 0.2.17 was yanked

### ISSUE THREAD

**Issue by danieldk** [PyO3/pyo3-pack#148]
```
error: failed to compile `pyo3-pack v0.6.0`, intermediate artifacts can be found at `/tmp/cargo-installibhtoX`
Caused by:
  failed to select a version for the requirement `structopt = "^0.2.17"`
  candidate versions found which didn't match: 0.2.16, 0.2.15, 0.2.14, ...
  location searched: crates.io index
required by package `pyo3-pack v0.6.0`
```

See: https://github.com/TeXitoi/structopt/issues/200

**Comment by konstin** [comment]
I thought that crates would keep building as long as that version is pinnend is Cargo.lock to avoid a leftpad-like disaster. Anyway, this needs to be fixed either way.

**Comment by danieldk** [comment]
Thanks for fixing this! Any chance you could also upload 0.6.1 to crates.io?

**Comment by konstin** [comment]
Oh sorry, I've uploaded 0.6.1 now.
