### ISSUE TITLE
pyo3_mixed not working properly on macOS

### ISSUE THREAD

**Issue by Renmusxd** [PyO3/pyo3-pack#162]
When running `pyo3-pack develop` in the `test_crates/pyo3-mixed` directory, a dynamic library is placed in the site-packages but the python module is left unused. This also holds for `pyo3-pack build` then `pip install target/wheels/*` -- the rust extension is able to be imported properly with `import pyo3_mixed` but the `get_42()` function call is not available (rust function `get_21()` works however).

I'm having the same issue with my own project developed with pyo3-pack. I haven't yet had the chance to check running this on linux.

**Comment by konstin** [comment]
Which version of pyo3-pack are you using? The support for mixed projects will be part of 0.7.0, for which I haven't made the final release yet.

**Comment by Renmusxd** [comment]
Ah, looks like I was using 0.6.X despite having thought I installed 0.7 (due to beta). Sorry to bother you, and thanks for the quick response.
