### ISSUE TITLE
Unable to pip install mixed layout project

### ISSUE THREAD

**Issue by pattonw** [PyO3/pyo3-pack#165]
There seems to be a problem with pip installing a mixed layout project where it doesn't place the compiled rust code into the project folder.

I made the following changes to pyo3-pack:
- in "pyo3-pack/test-crates/pyo3-mixed/pyproject.toml" I changed `requires = ["pyo3-pack"]` to `requires = ["pyo3-pack==0.7.0-beta.7"]`
- in "pyo3-pack/test-crates/pyo3-mixed/rust-toolchain" I changed `nightly` to `nightly-2019-07-01` since I couldn't get mashup to compile on the most recent nightly.

Using this setup I cd'd into the pyo3-mixed test crate and ran `pip install .`
This runs without an error, however when I open python and try to import pyo3_mixed I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pattonw/Work/Packages/pyo3-pack/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ModuleNotFoundError: No module named 'pyo3_mixed.pyo3_mixed'
```

This seems like it can't find the python functions created by rust in they python code directory, so I ran `pyo3-pack develop` which created the file "pyo3-pack/test-crates/pyo3-imxed/pyo3_mixed/pyo3_mixed.cpython-37m-x86_64-linux-gnu.so"

With this file created, `pip install .`, `import pyo3_mixed`, and `pyo3_mixed.get_42()` all work as expected.

**Comment by konstin** [comment]
Could it be that you're running the `import pyo3_mixed in `pyo3-pack/test-crates/pyo3-mixed/`, so that it imports from the local directory instead from the installed package?

**Comment by pattonw** [comment]
mmm, yeah, my bad that was the problem
