### ISSUE TITLE
pyo3-pack fails if no python3 executable is present

### ISSUE THREAD

**Issue by jrast** [PyO3/pyo3-pack#166]
If `pyo3-pack develop` is called and no interpreter named `python3` is present the setup fails:

```
(venv) PS D:\Entwicklung\Rust\python-extension> pyo3-pack.exe develop
🔗 Found pyo3 bindings
python3 doesn't exist
```
After creating a copy of `python.exe` with the name `python3.exe` the call was successful.

System Information:
- Windows 10
- Python 3.7.2 64bit in a virtualenv
- pyo3-pack 0.6.1

**Comment by konstin** [comment]
Could you try the latest beta release (`pip install --pre pyo3-pack`)? I think it's fixed there.

**Comment by jrast** [comment]
Yep, using the beta works! Output:
 
```
🔗 Found pyo3 bindings
🐍 Found CPython 3.7 at python.exe
   Compiling demo_pkg v0.1.0 (D:\Entwicklung\Rust\python-extension)
    Finished dev [unoptimized + debuginfo] target(s) in 2.12s
```
