### ISSUE TITLE
Support Metadata-Version in package.metadata.pyo3-pack

### ISSUE THREAD

**Issue by woelper** [PyO3/pyo3-pack#175]
First off, I have to use artifactory which does not support Metadata-Version higher than 2.0, so this strange feature request stems from that.

In the `Python metadata` section the docs state _"You can use other fields from the python core metadata in the [package.metadata.pyo3-pack] section (...)"_. I was somehow expecting I could override/set the Metadata-Version in this way by declaring something like:
```
[package.metadata.pyo3-pack]
metadata-version = "2.0"
```
Does this make sense to support? If you point me to the right direction I can try to do a PR myself.

**Comment by konstin** [comment]
Are you sure that artifactory supports Metadata-Version up to 2.0? The 2.0 was draft was discarded and 2.1 is essentially 1.2 with some small additions. The [specification](https://packaging.python.org/specifications/core-metadata/#metadata-version) of `Metadata-Version` says :

> Version of the file format; legal values are “1.0”, “1.1”, “1.2” and “2.1”.

From what I could find with google, there's also [this artifactory bug](https://www.jfrog.com/jira/browse/RTFACT-17020) for metadata version 2.1 which seems to have been resolved.

**Comment by woelper** [comment]
First of all, a big thank you for looking into this issue. I have to confess I am not sure of the 2.0 support, I have assumed it to be the case after downloading some wheels from our repo and `wheel unpack`ing them. They all had metadata 2.0.
Further, unfortunately, our company size somehow means that updates are slow and I have limited leverage in speeding up updating artifactory - that's why I am interested in working around the problem although I know it's probably not the optimal way. I currently unpack the pyo3-built wheel, replace the string 2.1 with 2.0 (yes, I feel dirty), pack it and upload it. My selfish thought was that by making the version user-configurable I would be able to work around the problem more easily...

**Comment by konstin** [comment]
I'm sorry, but I don't want to support bugs in old software that require violating the metadata PEPs. IMHO dirty patching and waiting for a software update is the most reasonable way to deal with a case like that.

**Comment by woelper** [comment]
Absolutely reasonable. Thanks for looking into that anyways!
