### ISSUE TITLE
Installation of beta release

### ISSUE THREAD

**Issue by clbarnes** [PyO3/pyo3-pack#187]
Ubuntu 16.04, python 3.7.3, rustc 1.37.0-nightly (02564de47 2019-06-10), cargo 1.37.0-nightly (545f35425 2019-05-23)

- Installing from source (download github release tarball -> `pip install .`) says it can't find the build backend (it does seem to rely on itself in the `pyproject.toml` [1])
- Trying to pip install from github does the same
- Installing from the deb places a file called pyo3-pack in `/usr/bin/`. The file exists, is executable, and is picked up by `which`. Trying to use it gives "command not found" in zsh and "No such file or directory" in bash
- Downloading the binary gz and placing it somewhere on the path: same as above

[1] trying to bootstrap with an earlier release doesn't help

**Comment by konstin** [comment]
Try running pip with `--pre`; That problem should be fixed with publishing a stable release.

**Comment by clbarnes** [comment]
Thanks, `--pre` works for me.
