### ISSUE TITLE
Trove classifiers

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3-pack#32]
Thoughts on adding support for trove classifiers for pypi?

Possibly something like:

```toml
[package.metadata.pyo3-pack.metadata]
classifier = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
]
```

This is somewhat consistent with the `[package.metadata.pyo3-pack.scripts]` mentioned in the README.

**Comment by konstin** [comment]
I'd like that!

**Comment by konstin** [comment]
This should be really easy to implement. Just parse a classifier key (type `Vec<String>` from `[package.metadata.pyo3-pack]`, similar to `scripts` is currently parsed, and fill the relevant `Metadata21` field:

https://github.com/PyO3/pyo3-pack/blob/eeaa4b4d4a40c7551fd94123a037e92a3998eed3/src/metadata.rs#L46
