### ISSUE TITLE
Windows and Mac testing

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3-pack#4]
pyo3-pack is meant as a replacement for setuptools-rust and is as such feature complete. As I'm working primarily on linux, I did only very limited tests on windows and don't have any mac to test on. It'd appreciate help testing those platforms. 

To install pyo3-pack, you can use a [prebuilt binary](https://github.com/PyO3/pyo3-pack/releases/latest) or `cargo install pyo3-pack`. For testing you can take any pyo3-powered python extension (e.g. hyperjson, pyo3's example or rust-numpy's example), build it, install it with pip and check if you can import it. I'd also be interested in feedback on the user experience (e.g. incomprehensible error message that showed up).

CC @althonos @mre @fafhrd91

**Comment by konstin** [comment]
@ManifoldFR you might want to try this for point-process-rust

**Comment by konstin** [comment]
Oh well, it shouldn't check for many*linux* compliancy on mac :sweat_smile: I've fixed it in e6a2de8197c2a0b2e2a5fd3c3dcfdac30cfc4e65.

>  Can I get rid of setuptools-rust entirely (also in setup.py)?

Yes, pyo3-pack is zero configuration and needs only a rust crate. Now that you already have a setuptools configuration it's imho a good idea to keep it as pyo3-pack won't be able to build source distribution for a while (those get compiled when installed, so package can be installed on python versions and platforms for which there are no wheels. The culprit in this case is pip though. See #2) I've tried to make this a bit clearer in the readme.

**Comment by mre** [comment]
After your fix it works!
Here's the output from my machine using the latest pyo3-pack from master:

```
~/C/p/hyperjson ❯❯❯ pyo3-pack build                                                                                                                                                                      
Found Python 2.7m at python2.7, Python 3.6m at python3.6, Python 3.7m at python3.7
Building the crate for Python 2.7m at python2.7
Building the wheel to /Users/mendler/Code/private/hyperjson/target/wheels/hyperjson-0.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building the crate for Python 3.6m at python3.6
Building the wheel to /Users/mendler/Code/private/hyperjson/target/wheels/hyperjson-0.1.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building the crate for Python 3.7m at python3.7
Building the wheel to /Users/mendler/Code/private/hyperjson
~/C/p/hyperjson ❯❯❯ l target/wheels/hyperjson-0.1.0-cp*                                                                                                                                                  
Permissions Size User    Date Modified Name
.rw-r--r--  677k mendler 10 Aug  0:01  target/wheels/hyperjson-0.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
.rw-r--r--  667k mendler 10 Aug  0:02  target/wheels/hyperjson-0.1.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
.rw-r--r--  667k mendler 10 Aug  0:02  target/wheels/hyperjson-0.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
~/C/p/hyperjson ❯❯❯ pip install target/wheels/hyperjson-0.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
~/C/p/hyperjson ❯❯❯ pip install --force-reinstall target/wheels/hyperjson-0.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Processing ./target/wheels/hyperjson-0.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: hyperjson
  Found existing installation: hyperjson 0.1
    Uninstalling hyperjson-0.1:
      Successfully uninstalled hyperjson-0.1
Successfully installed hyperjson-0.1.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~/C/p/hyperjson ❯❯❯ python
Python 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyperjson
>>> hyperjson.loads("1")
1
```

Thanks for that! I guess we can use it to publish hyperjson on pypi.
The next step would be building the wheels for Linux, probably with manylinux. I haven't worked with that before, so if you have any documentation on how to integrate that with pyo3-pack, that would be helpful.

**Comment by konstin** [comment]
Nice to hear in works on mac!

You don't need to do anything manylinux-related. pyo3-pack includes an auditwheel reimplementation and checks your libraries for compliance automatically.
