### ISSUE TITLE
Enable cargo feature when building

### ISSUE THREAD

**Issue by mehcode** [PyO3/pyo3-pack#45]
Tried using

```
❯ pyo3-pack build -b pyo3 --cargo-extra-args --features bridge-python
error: Found argument '--features' which wasn't expected, or isn't valid in this context

**Comment by konstin** [comment]
As stated in the readme, there is no `--features` option, but a general `--cargo-extra-args`.

**Comment by mehcode** [comment]
@konstin Apologies, but how do I use `--cargo-extra-args`? I've tried both the shown command and `--cargo-extra-args "--features bridge-python"` and neither works.
