### ISSUE TITLE
Does not handle conda environments on windows

### ISSUE THREAD

**Issue by paddyhoran** [PyO3/pyo3-pack#46]
Many windows users use `conda` environments to manage their python versions.  pyo3-pack does not seem to handle them well.

`pyo3-pack develop` mentions that I should be in a `venv`, but I am in a virtual environment.  It's just that I am using `conda` not `venv`.

`pyo3-pack` relies on the python launcher, which is not installed with conda (there is a standalone installer but it does not seem to play nice with conda).  The information regarding available interpreters can be gotten from `conda info -e`

**Comment by konstin** [comment]
While there are many scientific packages supporting both, anaconda/miniconda and pip/venv/virtualenv are two different ecosystems with different package managers, package formats and environments. You can [use pip's wheel files with conda](https://conda.io/docs/user-guide/tasks/build-packages/wheel-files.html), but apparently that's more of an workaround for libraries without conda packages.

I've actually never worked with conda, so I can't help with adding conda support. I assume it's possible to build wheels and maybe also install them in conda environment, but real `develop` support like for virtualenvs will difficult. Anyway, I'm happy to take patches that make some features available on conda or at least show propers error messages about conda not being supported.

**Comment by paddyhoran** [comment]
> You can [use pip's wheel files with conda](https://conda.io/docs/user-guide/tasks/build-packages/wheel-files.html), but apparently that's more of an workaround for libraries without conda packages.

Using pip wheels in a conda environment has worked flawlessly for me.  I just want to be able to build a wheel using my conda environment.

I'm taking a look and trying to find a way to make it work, I may ask a few questions as I work toward a PR, hope that's ok...

One fundamental question I have is why can't we just use the `python` found on the `PATH`?  This way I could just make sure I activate my development environment and build the wheel.

I see from the code that you search for all the installed interpreters, why do we need to do this?  Obviously, I'm missing something fundamental?  (The only reason I can think of is that you somehow make the resulting wheel compatible with all interpreters, although this seems wrong).

Thanks for this great package!

**Comment by konstin** [comment]
> One fundamental question I have is why can't we just use the python found on the PATH? This way I could just make sure I activate my development environment and build the wheel.

pyo3 and rust-cpython are using parts of the unstable python c abi, which is different for each python release and for different abiflags (which in practice only differ for debug builds for python 3). This means for those bindings we must build a package for each abi, which I try doing by just using all findable python versions. I've written a [blog post](https://blog.schuetze.link/2018/07/21/a-dive-into-packaging-native-python-extensions.html) which goes into greater detail.

> I'm taking a look and trying to find a way to make it work, I may ask a few questions as I work toward a PR, hope that's ok...

Sure, feel free to ask!

**Comment by konstin** [comment]
Fixed by #52
