### ISSUE TITLE
Error with passing flag as rustc extra arg.

### ISSUE THREAD

**Issue by JangYeeun** [PyO3/pyo3-pack#53]
The Readme says:
```
--rustc-extra-args <rustc_extra_args>...
           Extra arguments that will be passed to rustc as `cargo rustc [...] -- [arg1] [arg2]`
```

If I run
```
pyo3-pack build --rustc-extra-args -Awarnings
```
I get an error
```
error: Found argument '-A' which wasn't expected, ...
```

Is passing flags and options as arguments not supported? Otherwise how am I supposed to pass them?

**Comment by konstin** [comment]
You need to put the options in quotes or you're shell will interpret each as individual argument

**Comment by JangYeeun** [comment]
```
pyo3-pack build --rustc-extra-args "-Awarnings"
pyo3-pack build "--rustc-extra-args -Awarnings"
pyo3-pack "build --rustc-extra-args -Awarnings"
```
All fail in bash shell and zsh shell. I don't think shell has anything to do with this as - to my knowledge - it doesn't interpret arguments.

I think that because `-Awarnings` starts with single dash, clap is trying to interpret it as another switch.
When passing arguments to cargo that are supposed to be passed to rustc you need to pass them after `--` as in
```
cargo rustc – -Awarnings
```
which means that they will only be interpreted as positional aruments, not options.

**Comment by konstin** [comment]
Oh in this case you also need a `=`: `--rustc-extra-args="-Awarnings"`. If added that to the help and the readme
