### ISSUE TITLE
manylinux2010 / PEP 571

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3-pack#69]
pip 19.0 supports the tag: https://pip.pypa.io/en/stable/news/

https://www.python.org/dev/peps/pep-0571/

**Comment by ijl** [comment]
I can implement this.

**Comment by konstin** [comment]
Oh sorry, I though I had already tagged that. I've now released current master as 0.5.0-beta.4. I plan to publish 0.5.0 once https://github.com/eqrion/cbindgen/pull/271 is released, so I can publish on crates.io again.
