### ISSUE TITLE
Collecting extra file use cases

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3-pack#72]
For some projects it's necessary to add more files than those generated by pyo3-pack. Doing this is more difficult than for pure python projects because we don't have a classic source directory we just copy over. We also can't use cargo's includes/exclude because they might only be valid for the rust package. This issue is meant to collect what cases need to be considered.

**If you have a usecase where you need to add extra files, please add it here.** Information about whether the file is in the cargo includes/excludes and where it should go when installing the wheel (or where it should be inside the wheel) would be helpful.

**Comment by ijl** [comment]
The issue I ran into when trying to include a `pyi` file is that the shared object is put in `site-packages` and Python doesn't look for anything but metadata the `dist-info` dir. The only other use case I can think of right now is licenses and docs. I have a branch that can handle that. I think packing anything that can be used by Python is ruled out, though.

**Comment by robertodr** [comment]
I have a Python package and i would like to rewrite some portions of it in Rust. I'd need to copy the Python files alongside the compiled library, like so:
```
package/
    __init__.py
    stuff.py
    package.cpython-37m-x86_64-linux-gnu.so
```
Maybe there's already a way of achieving this?
