### ISSUE TITLE
Source distribution of pyo3-pack

### ISSUE THREAD

**Issue by robertodr** [PyO3/pyo3-pack#86]
Would it be possible to provide a source distribution of `pyo3-pack`? Pipenv cannot install it on NixOS which is not manylinux-compatible.

**Comment by konstin** [comment]
That depends on #2 being solved. There is however a (slightly outdated) nixos package (https://github.com/NixOS/nixpkgs/pull/46754) and you can also download pre-built binaries (https://github.com/PyO3/pyo3-pack/releases/latest)

**Comment by robertodr** [comment]
:man_facepalming: I feel like an idiot, I completely missed the NixOS package! Thanks a lot!

**Comment by robertodr** [comment]
I've sent a PR to update the NixOS package: https://github.com/NixOS/nixpkgs/pull/56032

**Comment by robertodr** [comment]
The PR has been merged :confetti_ball: Closing this issue.
