### ISSUE TITLE
Mixed project layout

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3-pack#88]
This layout makes it possible to combine a python project with a native rust extension. The minimal structure would look like the following:

```
my_proj
  src
    lib.rs
  my_proj
    __init__.py
  Cargo.toml
```

pyo3-pack would add either the shared library (for pyo3 and rust-cpython) or a folder with the shared library and some glue code (for cffi) in `__init__.py` in the `my_proj/my_proj` directoy. The module is named after the lib name in the Cargo.toml.

It should be possible to auto-detect this layout. It would also fix the problem of adding a `.pyi` file.

**Comment by fcangialosi** [comment]
I have exactly this structure. In the meantime until this feature is implemented, is it possible for me to do this manually? Or do I need to publish two separate packages: one for the native rust extension and one for the python module that imports it?

**Comment by konstin** [comment]
Currently you either need to publish two packages or use [setuptools-rust](https://github.com/PyO3/setuptools-rust)
