### ISSUE TITLE
Improvements for build.rs usage

### ISSUE THREAD

**Issue by ethanhs** [PyO3/pyo3-pack#93]
I have a project that has a custom `build.rs` script. Ideally, pyo3-pack would be able to pass the information about the interpreter being used to compile the rust crate to the script, so that any additional library needing to include/link to CPython can re-use this information and I don't need to re-compute it.

Perhaps it can be passed as environment variables when invoking cargo?

**Comment by konstin** [comment]
pyo3-pack already passes this information as `PYTHON_SYS_EXECUTABLE`, it's just not mentioned in the readme:

https://github.com/PyO3/pyo3-pack/blob/018ab0022910a77a12cb494786dc83cf5a04247f/src/compile.rs#L213-L215

**Comment by ethanhs** [comment]
I think that is an acceptable solution. Thanks!

**Comment by konstin** [comment]
BTW I'm open to passing more information (e.g. version numbers) and this should be documented properly somewhere.

**Comment by ethanhs** [comment]
Yeah perhaps this should be re-opened then (at least to document it). I think giving information given by `sysconfig.get_config_vars()` might be useful. But then again it may also be sufficient to leave it to others to shell out to Python to ask what they want?

**Comment by konstin** [comment]
I've added the following to the readme:

> pyo3 will set the used python interpreter in the environment variable `PYTHON_SYS_EXECUTABLE`, which can be used from custom build scripts.

**Comment by konstin** [comment]
If there's more information that pyo3-pack should pass on, please open a new issue
