### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by TyberiusPrime** [PyO3/pyo3-pack#99]
So I've successfully written and published my first python-rust module with pyo3 and pyo3-pack, and it's been a pretty painless process (and I thank you for that!).
Als, pypi does not show my Readme.md (or an README.md for that matter).

Is this not supported (yet) or am I doing something wrong?

I published with pyo3-pack publish, 
this is the github: https://github.com/TyberiusPrime/mbf_gtf 
and the pypi packages can be seen here https://pypi.org/project/mbf_gtf/

**Comment by konstin** [comment]
You need to set the `readme` key in Cargo.toml as described [in the cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata).

---

Btw it's great to see someone use pyo3-pack for a fast GTF parser. I've also recently written a (fairly basic)  fast GTF parser, even though it had to be in java 🧬

**Comment by TyberiusPrime** [comment]
Thank you for your quick response - in my defense I've started working with rust on monday, and haven't gotten to the cargo docs yet. This has been quite the rabbit hole...

---
My parser is awfully specialized to the Ensembl GTF variant. On the other hand, it's down from 120s of parsing with https://pypi.org/project/gtfparse/ to 10s - and 2 if you restrict what features you want to get back.
